services:
#  cdp-service:
#    type: application
#  wcs-service:
#    type: application
  mns-customer-personalisation-cdp-registration-read:
    type: application
  mns-customer-personalisation-cdp-registration-read_write:
    type: application