name: Run gitops to create topics, service accounts and acls
on:
  push:
    branches:
      - gitops
    paths-ignore:
      - '**.md'
      - '.github/*'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gitops
    strategy:
      matrix:
        env: [ "dev" ]
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gitops
      - name: Run script file
        run: |
          export CCLOUD_EMAIL=${{ secrets.CCLOUD_EMAIL }}
          export CCLOUD_PASSWORD=${{ secrets.CCLOUD_PASSWORD }}

          mkdir ccloud
          curl -L --http1.1 https://cnfl.io/ccloud-cli | sh -s -- -b ./ccloud
          export PATH=./ccloud:$PATH;

          ccloud login

          unzip \*.zip

          export XX_CCLOUD_EMAIL=$CCLOUD_EMAIL
          export XX_CCLOUD_PASSWORD=$CCLOUD_PASSWORD
          export KAFKA_BOOTSTRAP_SERVERS=${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
          export KAFKA_SASL_JAAS_USERNAME=${{ secrets.KAFKA_SASL_JAAS_USERNAME }}
          export KAFKA_SASL_JAAS_PASSWORD=${{ secrets.KAFKA_SASL_JAAS_PASSWORD }}
          export KAFKA_SECURITY_PROTOCOL=${{ secrets.KAFKA_SECURITY_PROTOCOL }}
          export KAFKA_SASL_MECHANISM=${{ secrets.KAFKA_SASL_MECHANISM }}
          export KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=${{ secrets.KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM }}

          chmod +x kafka-gitops
          mv kafka-gitops /usr/local/bin
          kafka-gitops --file state.yaml validate
          kafka-gitops account
          kafka-gitops --file state.yaml plan -o plan.json
          kafka-gitops --file state.yaml apply -p plan.json
