# This is a basic workflow to help you get started with Actions
name: Kafka Gitops
env:
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "PLAIN"
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gitops ]
    paths-ignore:
      - '**.md'
      - '.github/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: gitops

    environment: digital-development-33790

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run script
        run: |
          export CCLOUD_EMAIL=${{ secrets.CCLOUD_EMAIL }}
          export CCLOUD_PASSWORD=${{ secrets.CCLOUD_PASSWORD }}
          export KAFKA_BOOTSTRAP_SERVERS=${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
          export KAFKA_SASL_JAAS_USERNAME=${{ secrets.KAFKA_SASL_JAAS_USERNAME }}
          export KAFKA_SASL_JAAS_PASSWORD=${{ secrets.KAFKA_SASL_JAAS_PASSWORD }}
          export KAFKA_SECURITY_PROTOCOL=${{ env.KAFKA_SECURITY_PROTOCOL }}
          export KAFKA_SASL_MECHANISM=${{ env.KAFKA_SASL_MECHANISM }}
          export KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=${{ env.KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM }}

          chmod +x ./gitops-script-file.sh
          bash ./gitops-script-file.sh
