name: Run create user role script
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - '.github/*'
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ./scripts/create-user-role.sh
          mkdir ccloud
          curl -L --http1.1 https://cnfl.io/ccloud-cli | sh -s -- -b ./ccloud
          export PATH=./ccloud:$PATH;
          export CCLOUD_EMAIL="abnair2016@gmail.com"
          export CCLOUD_PASSWORD="7PgUJFYq\$aR\$4mW"
          echo "$CCLOUD_EMAIL::$CCLOUD_PASSWORD"
          ccloud login
          ENVIRONMENT_NAME=dev ROLE=EnvironmentAdmin EMAIL=abheeetest@gmail.com bash ./scripts/create-user-role.sh
