name: Run create user role script on manually triggered workflow
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - '.github/*'
  workflow_dispatch:
    inputs:
      email:
        description: 'Email(s)'
        required: true
        default: 'abheeetest@gmail.com'
      role:
        description: 'Role'
        required: true
        default: 'CloudClusterAdmin'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: scripts
    strategy:
      matrix:
        env: [ "dev", "test", "prod" ]
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          export CCLOUD_MIN_VERSION=2.0.0
          export CONFLUENT_CLOUD_EMAIL=${{ secrets.CCLOUD_EMAIL }}
          export CONFLUENT_CLOUD_PASSWORD=${{ secrets.CCLOUD_PASSWORD }}

          export ENVIRONMENT_NAME="${{ matrix.env }}"
          export EMAIL="${{ github.event.inputs.email }}"
          if [ -n "${{ github.event.inputs.role }}" ]
          then
            export ROLE="${{ github.event.inputs.role }}"
          else
            export ROLE="CloudClusterAdmin"
          fi

          echo "Email: $EMAIL"
          echo "Environment Name: $ENVIRONMENT_NAME"
          echo "Role: $ROLE"

          mkdir ccloud
          curl -L --http1.1 https://cnfl.io/ccloud-cli | sh -s -- -b ./ccloud latest
          export PATH=./ccloud:$PATH;
          ccloud update --major -y
          export PATH=./confluent:$PATH;
          confluent login

          chmod +x ./create-user-role.sh
          bash ./create-user-role.sh
