name: Run create user role script on manually triggered workflow
on:
#  push:
#    branches:
#      - master
#      - main
#    paths-ignore:
#      - '**.md'
#      - '.github/*'
#  pull_request:
#    branches:
#      - master
#      - main
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'Environment Name'
        required: true
        default: 'dev'
      role:
        description: 'Role'
        required: true
        default: 'CloudClusterAdmin'
      email:
        description: 'Email'
        required: true
      clusterName:
        description: 'Cluster Name'
        required: false
        default: 'cluster_0'
      clusterCloud:
        description: 'Cluster Cloud Provider'
        required: false
        default: 'azure'
      clusterRegion:
        description: 'Cluster Cloud Region'
        required: false
        default: 'eastus'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          export CCLOUD_EMAIL=${{ secrets.CCLOUD_EMAIL }}
          export CCLOUD_PASSWORD=${{ secrets.CCLOUD_PASSWORD }}

          export ENVIRONMENT_NAME=${{ github.event.inputs.environmentName }}
          echo "Environment Name: $ENVIRONMENT_NAME"

          export ROLE=${{ github.event.inputs.role }}
          echo "Role: $ROLE"

          echo "${{ github.event.inputs.email }}"

          export EMAIL="${{ github.event.inputs.email }}"
          echo "Email: $EMAIL"

          export CLUSTER_NAME=${{ github.event.inputs.clusterName }}
          echo "Cluster Name: $CLUSTER_NAME"

          export CLUSTER_CLOUD=${{ github.event.inputs.clusterCloud }}
          echo "Cluster Cloud Provider: $CLUSTER_CLOUD"

          export CLUSTER_REGION=${{ github.event.inputs.clusterRegion }}
          echo "Cluster Region: $CLUSTER_REGION"

          chmod +x ./scripts/create-user-role.sh
          mkdir ccloud
          curl -L --http1.1 https://cnfl.io/ccloud-cli | sh -s -- -b ./ccloud
          export PATH=./ccloud:$PATH;

          ccloud login
          bash ./scripts/create-user-role.sh
